# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='v1',
  syntax='proto3',
  serialized_options=b'Z\004.;v1',
  serialized_pb=b'\n\x0cserver.proto\x12\x02v1\"&\n\tSubscribe\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0b\n\x03lab\x18\x02 \x03(\t\"u\n\x04Task\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.v1.Task.Type\x12\x10\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\x03\x12\x14\n\x0c\x64\x65scriptions\x18\x03 \x03(\t\"(\n\x04Type\x12\x08\n\x04TEST\x10\x00\x12\x0c\n\x08HOMEWORK\x10\x01\x12\x08\n\x04QUIZ\x10\x02\"9\n\x08Solution\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x10\n\x08solution\x18\x03 \x03(\x0c\"E\n\rGradeSolution\x12\x13\n\x0btime_graded\x18\x01 \x01(\x03\x12\r\n\x05grade\x18\x02 \x01(\x05\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x9f\x01\n\x0eStudentService\x12)\n\nSignForLab\x12\r.v1.Subscribe\x1a\x08.v1.Task\"\x00\x30\x01\x12\x33\n\x0cSendSolution\x12\x0c.v1.Solution\x1a\x11.v1.GradeSolution\"\x00\x30\x01\x12-\n\x14TESTCreateAssignment\x12\x08.v1.Task\x1a\t.v1.Empty\"\x00\x42\x06Z\x04.;v1b\x06proto3'
)



_TASK_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='v1.Task.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOMEWORK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIZ', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=137,
  serialized_end=177,
)
_sym_db.RegisterEnumDescriptor(_TASK_TYPE)


_SUBSCRIBE = _descriptor.Descriptor(
  name='Subscribe',
  full_name='v1.Subscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='v1.Subscribe.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lab', full_name='v1.Subscribe.lab', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=58,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='v1.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='v1.Task.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='v1.Task.deadline', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='descriptions', full_name='v1.Task.descriptions', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=177,
)


_SOLUTION = _descriptor.Descriptor(
  name='Solution',
  full_name='v1.Solution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='v1.Solution.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='v1.Solution.comment', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solution', full_name='v1.Solution.solution', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=236,
)


_GRADESOLUTION = _descriptor.Descriptor(
  name='GradeSolution',
  full_name='v1.GradeSolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_graded', full_name='v1.GradeSolution.time_graded', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grade', full_name='v1.GradeSolution.grade', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='v1.GradeSolution.feedback', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=307,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='v1.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=316,
)

_TASK.fields_by_name['type'].enum_type = _TASK_TYPE
_TASK_TYPE.containing_type = _TASK
DESCRIPTOR.message_types_by_name['Subscribe'] = _SUBSCRIBE
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Solution'] = _SOLUTION
DESCRIPTOR.message_types_by_name['GradeSolution'] = _GRADESOLUTION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subscribe = _reflection.GeneratedProtocolMessageType('Subscribe', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:v1.Subscribe)
  })
_sym_db.RegisterMessage(Subscribe)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:v1.Task)
  })
_sym_db.RegisterMessage(Task)

Solution = _reflection.GeneratedProtocolMessageType('Solution', (_message.Message,), {
  'DESCRIPTOR' : _SOLUTION,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:v1.Solution)
  })
_sym_db.RegisterMessage(Solution)

GradeSolution = _reflection.GeneratedProtocolMessageType('GradeSolution', (_message.Message,), {
  'DESCRIPTOR' : _GRADESOLUTION,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:v1.GradeSolution)
  })
_sym_db.RegisterMessage(GradeSolution)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:v1.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_STUDENTSERVICE = _descriptor.ServiceDescriptor(
  name='StudentService',
  full_name='v1.StudentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=319,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignForLab',
    full_name='v1.StudentService.SignForLab',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBE,
    output_type=_TASK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSolution',
    full_name='v1.StudentService.SendSolution',
    index=1,
    containing_service=None,
    input_type=_SOLUTION,
    output_type=_GRADESOLUTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TESTCreateAssignment',
    full_name='v1.StudentService.TESTCreateAssignment',
    index=2,
    containing_service=None,
    input_type=_TASK,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUDENTSERVICE)

DESCRIPTOR.services_by_name['StudentService'] = _STUDENTSERVICE

# @@protoc_insertion_point(module_scope)
